
import { Translations, Language } from './types';

export const TRANSLATIONS: Record<Language, Translations> = {
  tr: {
    title: "Patnos Dama",
    subtitle: "İzmir Patnoslular Derneği Yapımıdır",
    turn: "Sıra",
    white: "Mavi",
    black: "Sarı",
    restart: "Yeni Oyun",
    undo: "Geri Al",
    aiAnalysis: "Yapay Zeka Analizi",
    winner: "Kazanan",
    thinking: "Düşünüyor...",
    noSelection: "Hamle yapmak için bir taş seçin.",
    moveHelp: "Patnos kuralları: Sadece ileri ve yanlara. En çok taş yeme zorunludur!",
    difficulty: "Zorluk",
    beginner: "Acemi",
    normal: "Normal",
    expert: "Uzman",
    mandatoryCapture: "Mecburi alış var! En çok taş yiyeceğiniz hamleyi yapmalısınız.",
    opponentOffering: "Dikkat! Rakip taş istedi (Mecburi alış).",
    setupProfile: "Profilini Oluştur",
    enterName: "Adınızı girin",
    startGame: "Oyuna Başla",
    choosePhoto: "Fotoğraf Seç",
    timeout: "SÜRE DOLDU",
    analyze: "ANALİZ",
    aiFallback: "Yapay zeka artık hamlelerini tahmin ediyor ve damaya gidiş yollarını kapatmaya odaklanıyor!",
    engine: "MOTORU",
    versionInfo: "TAHMİNSEL STRATEJİ"
  },
  ku: {
    title: "Dama Patnosê",
    subtitle: "İzmir Patnoslular Derneği Yapımıdır",
    turn: "Dor",
    white: "Şîn",
    black: "Zer",
    restart: "Lîstika Nû",
    undo: "Paşve Biçe",
    aiAnalysis: "Analîza Zîrekiya Sûnî",
    winner: "Serketî",
    thinking: "Difikire...",
    noSelection: "Ji bo tevgerê kevirêk hilbijêre.",
    moveHelp: "Rêzikên Patnosê: Bi tenê pêş û her du alî. Xwarina herî zêde mecbûrî ye!",
    difficulty: "Zorî",
    beginner: "Sade",
    normal: "Normal",
    expert: "Pispor",
    mandatoryCapture: "Xwarina mecbûrî heye! Divê tu tevgera herî zêde xwarinê bikî.",
    opponentOffering: "Hişyar bî! Dijber kevir xwest (Xwarina mecbûrî).",
    setupProfile: "Profîla Xwe Ava Bike",
    enterName: "Navê xwe binivîse",
    startGame: "Dest bi Lîstikê Bike",
    choosePhoto: "Wêne Hilbijêre",
    timeout: "DEM XILAS BÛ",
    analyze: "ANALÎZ",
    aiFallback: "Zîrekiya sûnî niha tevgerên we pêşbînî dike û bala xwe dide ser girtina rêyên damayê!",
    engine: "MOTORÊ",
    versionInfo: "STRATEJIYA PÊŞBÎNÎ"
  },
  en: {
    title: "Patnos Draughts",
    subtitle: "İzmir Patnoslular Derneği Yapımıdır",
    turn: "Turn",
    white: "Blue",
    black: "Yellow",
    restart: "New Game",
    undo: "Undo",
    aiAnalysis: "AI Analysis",
    winner: "Winner",
    thinking: "Thinking...",
    noSelection: "Select a piece to move.",
    moveHelp: "Patnos Rules: Only forward and sides. Maximum capture is mandatory!",
    difficulty: "Difficulty",
    beginner: "Beginner",
    normal: "Normal",
    expert: "Expert",
    mandatoryCapture: "Mandatory capture! You must make the move that captures the most pieces.",
    opponentOffering: "Watch out! Opponent is offering a piece (Mandatory capture).",
    setupProfile: "Setup Your Profile",
    enterName: "Enter your name",
    startGame: "Start Game",
    choosePhoto: "Choose Photo",
    timeout: "TIME OUT",
    analyze: "ANALYZE",
    aiFallback: "AI now predicts your moves and focuses on blocking your path to becoming a king!",
    engine: "ENGINE",
    versionInfo: "PREDICTIVE STRATEGY"
  }
};
